-- begin CUBAFILTERDEMO_PATIENT
alter table CUBAFILTERDEMO_PATIENT add constraint FK_CUBAFILTERDEMO_PATIENT_DIAGNOSIS foreign key (DIAGNOSIS_ID) references CUBAFILTERDEMO_DIAGNOSIS(ID)^
alter table CUBAFILTERDEMO_PATIENT add constraint FK_CUBAFILTERDEMO_PATIENT_SIBLING foreign key (SIBLING_ID) references CUBAFILTERDEMO_SIBLING(ID)^
create index IDX_CUBAFILTERDEMO_PATIENT_DIAGNOSIS on CUBAFILTERDEMO_PATIENT (DIAGNOSIS_ID)^
-- end CUBAFILTERDEMO_PATIENT
-- begin CUBAFILTERDEMO_DIAGNOSIS
alter table CUBAFILTERDEMO_DIAGNOSIS add constraint FK_CUBAFILTERDEMO_DIAGNOSIS_PARENT foreign key (PARENT_ID) references CUBAFILTERDEMO_DIAGNOSIS(ID)^
create index IDX_CUBAFILTERDEMO_DIAGNOSIS_PARENT on CUBAFILTERDEMO_DIAGNOSIS (PARENT_ID)^
-- end CUBAFILTERDEMO_DIAGNOSIS
-- begin CUBAFILTERDEMO_SIBLING
alter table CUBAFILTERDEMO_SIBLING add constraint FK_CUBAFILTERDEMO_SIBLING_DIAGNOSIS foreign key (DIAGNOSIS_ID) references CUBAFILTERDEMO_DIAGNOSIS(ID)^
create index IDX_CUBAFILTERDEMO_SIBLING_DIAGNOSIS on CUBAFILTERDEMO_SIBLING (DIAGNOSIS_ID)^
-- end CUBAFILTERDEMO_SIBLING
