alter table CUBAFILTERDEMO_SIBLING add constraint FK_CUBAFILTERDEMO_SIBLING_DIAGNOSIS foreign key (DIAGNOSIS_ID) references CUBAFILTERDEMO_DIAGNOSIS(ID);
create index IDX_CUBAFILTERDEMO_SIBLING_DIAGNOSIS on CUBAFILTERDEMO_SIBLING (DIAGNOSIS_ID);
